### ISSUE TITLE
Issue during build of pmt rhel86 branch

### ISSUE THREAD

**Issue by hershpa** [intel-gpu/intel-gpu-pmt-backports#2]
We are seeing the following issue during the build of the pmt driver. We are using kernel version: 4.18.0-372.19.1.el8_6.x86_64

Issue:
[1/2] STEP 9/10: RUN git clone -b rhel86 https://github.com/intel-gpu/intel-gpu-pmt-backports.git && cd intel-gpu-pmt-backports && make && make modules_install
Cloning into 'intel-gpu-pmt-backports'...
make -C drivers/platform/x86/intel
make[1]: Entering directory '/build/intel-gpu-pmt-backports/drivers/platform/x86/intel'
make -C /lib/modules/`uname -r`/build M=$PWD
make[2]: Entering directory '/usr/src/kernels/4.18.0-372.19.1.el8_6.x86_64'
  CC [M]  /build/intel-gpu-pmt-backports/drivers/platform/x86/intel/vsec.o
/build/intel-gpu-pmt-backports/drivers/platform/x86/intel/vsec.c:340:1: warning: data definition has no type or storage class
 EXPORT_SYMBOL_NS(intel_vsec_register, INTEL_VSEC);
 ^~~~~~~~~~~~~~~~
/build/intel-gpu-pmt-backports/drivers/platform/x86/intel/vsec.c:340:1: error: type defaults to 'int' in declaration of 'EXPORT_SYMBOL_NS' [-Werror=implicit-int]
/build/intel-gpu-pmt-backports/drivers/platform/x86/intel/vsec.c:340:1: warning: parameter names (without types) in function declaration
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:316: /build/intel-gpu-pmt-backports/drivers/platform/x86/intel/vsec.o] Error 1
make[2]: Leaving directory '/usr/src/kernels/4.18.0-372.19.1.el8_6.x86_64'
make[2]: *** [Makefile:1577: _module_/build/intel-gpu-pmt-backports/drivers/platform/x86/intel] Error 2

**Comment by eero-t** [comment]
@hershpa Is this bug still relevant after you filed #4 ?

**Comment by hershpa** [comment]
This was a separate issue but it has already been resolved, closing issue.
