### ISSUE TITLE
Build Issue of pmt rhel86 branch.

### ISSUE THREAD

**Issue by hershpa** [intel-gpu/intel-gpu-pmt-backports#4]
Observed the following error during build of pmt rhel86 branch. Please advise. 

[1/2] STEP 9/11: RUN git clone -b rhel86 https://github.com/intel-gpu/intel-gpu-pmt-backports.git && cd intel-gpu-pmt-backports && make && make modules_install
Cloning into 'intel-gpu-pmt-backports'...
scripts/generate_osv_version_h.sh > include/generated_osv_version.h
Failed to recognize version.\nPlease set correct OS_TYPE and/or OS_VERSION.\n\nGot:\nOS_TYPE=\nOS_VERSION=\n
make: *** [Makefile:8: include/generated_osv_version.h] Error 1
error: build error: error building at STEP "RUN git clone -b rhel86 https://github.com/intel-gpu/intel-gpu-pmt-backports.git && cd intel-gpu-pmt-backports && make && make modules_install": error while running runtime: exit status

**Comment by ArturKloniecki** [comment]
Please refer to the README file https://github.com/intel-gpu/intel-gpu-pmt-backports/blob/rhel86/README.md 
There are environment variables that need to be set to properly build the rpm.
