### ISSUE TITLE
RPM package version discrepancy between readme and what is actually created by Makefile.dkms

### ISSUE THREAD

**Issue by hershpa** [intel-gpu/intel-gpu-pmt-backports#6]
In the readme here: https://github.com/intel-gpu/intel-gpu-pmt-backports/tree/rhel85#build-and-install-dkms-package-1, it mentions "The rpm package will be placed in $HOME/rpmbuild/RPMS/x86_64. For example:

/home/user/rpmbuild/RPMS/x86_64/intel-platform-pmt-dkms-2022.7-1.x86_64.rpm" This is a version of year 2022.

However, the rpm package that is actually created by Makefile.dkms is of version of year 2021: intel-platform-pmt-dkms-2021.21-1.x86_64.rpm. 
Is this a typo in the readme as the readme specifies a rpm package of version 2022 being created? Want to double check if this is a readme issue or if there is actually a version 2022 rpm package that should be created by Makefile.dkms.

**Comment by tripzero** [comment]
The example is meant to specify the location of the RPM, not the exact package file that will be created -which will change over time.

**Comment by hershpa** [comment]
Thanks for confirming!
